# Generated by Django 4.0.6 on 2022-08-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
