# Generated by Django 4.0.6 on 2022-08-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('phone', models.CharField(max_length=300, unique=True)),
                ('job', models.CharField(max_length=300)),
                ('dept', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
    ]
