# Generated by Django 4.0.6 on 2022-08-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewSets', '0002_alter_employee_company_alter_employee_dept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usename', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=230)),
            ],
        ),
    ]
