# Generated by Django 4.0.6 on 2022-08-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ViewSets', '0003_empsignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empsignup',
            old_name='usename',
            new_name='username',
        ),
    ]
